server:
  port: 8000
  eurekapost: 10100
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/svs?serverTimezone=UTC
      username: root
      password: x5
  application:
    name: other-service
eureka:
  client:
    service-url:
     defaultZone: http://${eureka.instance.ip-address}:${server.eurekapost}/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1