server:
  port: 6000
  eurekapost: 10100
file:
  max-size: 100MB
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/svs?serverTimezone=UTC
      username: root
      password: x5
  application:
    name: Vadio-service
  servlet:
    multipart:
      max-file-size: ${file.max-size}
      max-request-size: ${file.max-size}
eureka:
  client:
    service-url:
     defaultZone: http://${eureka.instance.ip-address}:${server.eurekapost}/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
